package ec.com.tecnointel.soem.caja.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * CajaPeri generated by hbm2java
 */
@Entity
@Table(name = "caja_peri")
@NamedEntityGraph(name = "cajaPeri.Graph", attributeNodes = {
@NamedAttributeNode(value = "caja"),
@NamedAttributeNode(value = "periferico") })
public class CajaPeri implements java.io.Serializable {

	private Integer cajaPeriId;
	private Caja caja;
	private Periferico periferico;
	private Boolean acceso;

	private static final long serialVersionUID = 5419704500163541767L;

	public CajaPeri() {
	}

	public CajaPeri(Integer cajaPeriId, Caja caja, Periferico periferico, Boolean acceso) {
		this.cajaPeriId = cajaPeriId;
		this.caja = caja;
		this.periferico = periferico;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idCajaPeri", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "caja_peri", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idCajaPeri")
	@Column(name = "CAJA_PERI_ID", unique = true, nullable = false)
	public Integer getCajaPeriId() {
		return this.cajaPeriId;
	}

	public void setCajaPeriId(Integer cajaPeriId) {
		this.cajaPeriId = cajaPeriId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAJA_ID", nullable = false)
	public Caja getCaja() {
		return this.caja;
	}

	public void setCaja(Caja caja) {
		this.caja = caja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIFERICO_ID", nullable = false)
	public Periferico getPeriferico() {
		return this.periferico;
	}

	public void setPeriferico(Periferico periferico) {
		this.periferico = periferico;
	}

	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

}
