package ec.com.tecnointel.soem.contabilidad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TranDeta generated by hbm2java
 */
@Entity
@Table(name = "tran_deta")
@NamedEntityGraph(name = "tranDeta.Graph", attributeNodes = {
		@NamedAttributeNode(value = "planCuen")
})
public class TranDeta implements java.io.Serializable {

	private Integer tranDetaId;
	private PlanCuen planCuen;
	private Transaccion transaccion;
	private Date fechaEmis;
	private BigDecimal total;
	private String nota;

	private static final long serialVersionUID = 5407034900789938509L;

	public TranDeta() {
	}

	public TranDeta(Integer tranDetaId, PlanCuen planCuen, Transaccion transaccion, 
			Date fechaEmis, BigDecimal total) {
		this.tranDetaId = tranDetaId;
		this.planCuen = planCuen;
		this.transaccion = transaccion;
		this.fechaEmis = fechaEmis;
		this.total = total;
	}

	public TranDeta(Integer tranDetaId, PlanCuen planCuen, Date fechaEmis, Transaccion transaccion, BigDecimal total, String nota) {
		this.tranDetaId = tranDetaId;
		this.planCuen = planCuen;
		this.transaccion = transaccion;
		this.fechaEmis = fechaEmis;
		this.total = total;
		this.nota = nota;
	}

	@Id
	@TableGenerator(name = "idTranDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "tran_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTranDeta")
	@Column(name = "TRAN_DETA_ID", unique = true, nullable = false)
	public Integer getTranDetaId() {
		return this.tranDetaId;
	}

	public void setTranDetaId(Integer tranDetaId) {
		this.tranDetaId = tranDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACCION_ID", nullable = false)
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_EMIS", nullable = false, length = 10)
	public Date getFechaEmis() {
		return fechaEmis;
	}

	public void setFechaEmis(Date fechaEmis) {
		this.fechaEmis = fechaEmis;
	}

	@Column(name = "TOTAL", nullable = false, precision = 14, scale = 6)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}
}
