package ec.com.tecnointel.soem.ingreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedSubgraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Retencion generated by hbm2java
 */
@Entity
@Table(name = "retencion")
@NamedEntityGraph(name = "retencion.Graph", attributeNodes = {
	@NamedAttributeNode(value = "ingreso", subgraph = "persProv.Graph"),
},
subgraphs = {
		@NamedSubgraph(name = "persProv.Graph",attributeNodes =
			{ 
				@NamedAttributeNode(value = "persProv")
			}) 
		}
)
public class Retencion implements java.io.Serializable {

	private Integer retencionId;
	private Ingreso ingreso;
	private boolean documeElec;
	private Date fechaRegi;
	private Date fechaEmis;
	private Date fechaAuto;
	private String serie1;
	private String serie2;
	private Integer numero;
	private String autori;
	private String claveAcce;
	private String nota;
	private String estado;
	private String estadoDocuElec;
	private String motivoRech;
	private String leyen1;
	private String leyen2;
	private String msgInfoAdic;
	
	private Set<ReteDeta> reteDetas = new HashSet<ReteDeta>(0);

	private static final long serialVersionUID = 8346838988889150754L;

	public Retencion() {
	}

	public Retencion(Integer retencionId, Ingreso ingreso, boolean documeElec, Date fechaRegi, Date fechaEmis,
			Date fechaAuto, String serie1, String serie2, Integer numero, String autori, String claveAcce,
			String estado, String estadoDocuElec, String motivoRech, String leyen1, String leyen2) {
		this.retencionId = retencionId;
		this.ingreso = ingreso;
		this.documeElec = documeElec;
		this.fechaRegi = fechaRegi;
		this.fechaEmis = fechaEmis;
		this.fechaAuto = fechaAuto;
		this.serie1 = serie1;
		this.serie2 = serie2;
		this.numero = numero;
		this.autori = autori;
		this.claveAcce = claveAcce;
		this.estado = estado;
		this.estadoDocuElec = estadoDocuElec;
		this.motivoRech = motivoRech;
		this.leyen1 = leyen1;
		this.leyen2 = leyen2;
	}

	public Retencion(Integer retencionId, Ingreso ingreso, boolean documeElec, Date fechaRegi, Date fechaEmis,
			Date fechaAuto, String serie1, String serie2, Integer numero, String autori, String claveAcce, 
			String nota, String estado, String estadoDocuElec, String motivoRech, String leyen1, String leyen2, 
			Set<ReteDeta> reteDetas) {
		this.retencionId = retencionId;
		this.ingreso = ingreso;
		this.documeElec = documeElec;
		this.fechaRegi = fechaRegi;
		this.fechaEmis = fechaEmis;
		this.fechaAuto = fechaAuto;
		this.serie1 = serie1;
		this.serie2 = serie2;
		this.numero = numero;
		this.autori = autori;
		this.claveAcce = claveAcce;
		this.nota = nota;
		this.estado = estado;
		this.reteDetas = reteDetas;
		this.estadoDocuElec = estadoDocuElec;
		this.motivoRech = motivoRech;
		this.leyen1 = leyen1;
		this.leyen2 = leyen2;
	}

	@Id
	@TableGenerator(name = "idRetencion", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "retencion", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRetencion")
	@Column(name = "RETENCION_ID", unique = true, nullable = false)
	public Integer getRetencionId() {
		return this.retencionId;
	}

	public void setRetencionId(Integer retencionId) {
		this.retencionId = retencionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INGRESO_ID", nullable = false)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@Column(name = "DOCUME_ELEC", nullable = false)
	public boolean isDocumeElec() {
		return this.documeElec;
	}

	public void setDocumeElec(boolean documeElec) {
		this.documeElec = documeElec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGI", nullable = false, length = 10)
	public Date getFechaRegi() {
		return this.fechaRegi;
	}

	public void setFechaRegi(Date fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_EMIS", nullable = false, length = 10)
	public Date getFechaEmis() {
		return this.fechaEmis;
	}

	public void setFechaEmis(Date fechaEmis) {
		this.fechaEmis = fechaEmis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_AUTO", nullable = false, length = 19)
	public Date getFechaAuto() {
		return this.fechaAuto;
	}

	public void setFechaAuto(Date fechaAuto) {
		this.fechaAuto = fechaAuto;
	}

	@Column(name = "SERIE1", nullable = false, length = 3)
	public String getSerie1() {
		return this.serie1;
	}

	public void setSerie1(String serie1) {
		this.serie1 = serie1;
	}

	@Column(name = "SERIE2", nullable = false, length = 3)
	public String getSerie2() {
		return this.serie2;
	}

	public void setSerie2(String serie2) {
		this.serie2 = serie2;
	}

	@Column(name = "NUMERO", nullable = false, precision = 10, scale = 0)
	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "AUTORI", nullable = false, length = 60)
	public String getAutori() {
		return this.autori;
	}

	public void setAutori(String autori) {
		this.autori = autori;
	}

	@Column(name = "CLAVE_ACCE", nullable = false, length = 60)
	public String getClaveAcce() {
		return this.claveAcce;
	}

	public void setClaveAcce(String claveAcce) {
		this.claveAcce = claveAcce;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "ESTADO", nullable = false)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "ESTADO_DOCU_ELEC", nullable = false)
	public String getEstadoDocuElec() {
		return estadoDocuElec;
	}

	public void setEstadoDocuElec(String estadoDocuElec) {
		this.estadoDocuElec = estadoDocuElec;
	}

	@Column(name = "MOTIVO_RECH")
	public String getMotivoRech() {
		return motivoRech;
	}

	public void setMotivoRech(String motivoRech) {
		this.motivoRech = motivoRech;
	}

	@Column(name = "LEYEN1")
	public String getLeyen1() {
		return leyen1;
	}

	public void setLeyen1(String leyen1) {
		this.leyen1 = leyen1;
	}

	@Column(name = "LEYEN2")
	public String getLeyen2() {
		return leyen2;
	}

	public void setLeyen2(String leyen2) {
		this.leyen2 = leyen2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retencion", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	public Set<ReteDeta> getReteDetas() {
		return this.reteDetas;
	}

	public void setReteDetas(Set<ReteDeta> reteDetas) {
		this.reteDetas = reteDetas;
	}

	@Column(name = "MSG_INFO_ADIC")
	public String getMsgInfoAdic() {
		return msgInfoAdic;
	}

	public void setMsgInfoAdic(String msgInfoAdic) {
		this.msgInfoAdic = msgInfoAdic;
	}

}
