package ec.com.tecnointel.soem.egreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

import ec.com.tecnointel.soem.inventario.modelo.Kardex;
import ec.com.tecnointel.soem.inventario.modelo.Producto;
import ec.com.tecnointel.soem.parametro.modelo.Precio;

/**
 * EgreDeta generated by hbm2java
 */
@Entity
@Table(name = "egre_deta")
@NamedEntityGraph(name = "egreDeta.Graph", attributeNodes = {
		@NamedAttributeNode(value = "producto"),
		@NamedAttributeNode(value = "egreso"),
		@NamedAttributeNode(value = "precio"),
})
public class EgreDeta implements java.io.Serializable {

	private Integer egreDetaId;
	private EgreDeta egreDeta;
	private Egreso egreso;
	private Producto producto;
	private Precio precio;
	private Date fechaRegi;
	private BigDecimal cantid;
	private BigDecimal factor;
	private BigDecimal precioVent;
	private BigDecimal descue;
	private BigDecimal costo;
	private String nota;
	
	private Set<EgreDetaImpu> egreDetaImpus = new HashSet<EgreDetaImpu>(0);
	private Set<Kardex> kardexs = new HashSet<Kardex>(0);
	private Set<EgreDeta> egreDetas = new HashSet<EgreDeta>(0);

	private BigDecimal precioConImpu;
	private BigDecimal totalConImpu;
	private BigDecimal total;
	
	private static final long serialVersionUID = 41994585451314546L;

	public EgreDeta() {
	}

	public EgreDeta(Egreso egreso, EgreDeta egreDeta) {
		this.egreso = egreso;
		this.egreDeta = egreDeta;
	}

	public EgreDeta(Integer egreDetaId, EgreDeta egreDeta, Egreso egreso, Producto producto, Precio precio, Date fechaRegi, 
			BigDecimal cantid, BigDecimal factor, BigDecimal precioVent, BigDecimal descue, 
			BigDecimal costo, String nota) {
		this.egreDetaId = egreDetaId;
		this.egreso = egreso;
		this.egreDeta = egreDeta;
		this.producto = producto;
		this.precio = precio;
		this.fechaRegi = fechaRegi;
		this.cantid = cantid;
		this.factor = factor;
		this.precioVent = precioVent;
		this.descue = descue;
		this.costo = costo;
		this.nota = nota;
	}

	public EgreDeta(Integer egreDetaId, EgreDeta egreDeta, Egreso egreso, Producto producto, Precio precio, Date fechaRegi, 
			BigDecimal cantid, BigDecimal factor, BigDecimal precioVent, BigDecimal descue, 
			BigDecimal costo, String nota, 
			Set<EgreDetaImpu> egreDetaImpus, Set<Kardex> kardexs) {
		this.egreDetaId = egreDetaId;
		this.egreso = egreso;
		this.egreDeta = egreDeta;
		this.producto = producto;
		this.precio = precio;
		this.fechaRegi = fechaRegi;
		this.cantid = cantid;
		this.factor = factor;
		this.precioVent = precioVent;
		this.descue = descue;
		this.costo = costo;
		this.nota = nota;
		this.egreDetaImpus = egreDetaImpus;
	    this.kardexs = kardexs;
	}

	@Id
	@TableGenerator(name = "idEgreDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "egre_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEgreDeta")
	@Column(name = "EGRE_DETA_ID", unique = true, nullable = false)
	public Integer getEgreDetaId() {
		return this.egreDetaId;
	}
	
	public void setEgreDetaId(Integer egreDetaId) {
		this.egreDetaId = egreDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EGRE_DETA_SUPE_ID")
	public EgreDeta getEgreDeta() {
		return egreDeta;
	}

	public void setEgreDeta(EgreDeta egreDeta) {
		this.egreDeta = egreDeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EGRESO_ID", nullable = false)
	public Egreso getEgreso() {
		return this.egreso;
	}

	public void setEgreso(Egreso egreso) {
		this.egreso = egreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_ID", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRECIO_ID", nullable = false)
	public Precio getPrecio() {
		return this.precio;
	}

	public void setPrecio(Precio precio) {
		this.precio = precio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_REGI", nullable = false, length = 10)
	public Date getFechaRegi() {
		return this.fechaRegi;
	}

	public void setFechaRegi(Date fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Column(name = "CANTID", nullable = false, precision = 12, scale = 6)
	@DecimalMin(value = "0.0001", message="No se permite valores negativos")
	public BigDecimal getCantid() {
		return this.cantid;
	}

	public void setCantid(BigDecimal cantid) {
		this.cantid = cantid;
	}

	@Column(name = "FACTOR", nullable = false, precision = 12, scale = 6)
	public BigDecimal getFactor() {
		return factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}
	
	@Column(name = "PRECIO_VENT", nullable = false, precision = 12, scale = 6)
	public BigDecimal getPrecioVent() {
		return this.precioVent;
	}

	public void setPrecioVent(BigDecimal precioVent) {
		this.precioVent = precioVent;
	}

	@Column(name = "DESCUE", nullable = false, precision = 8, scale = 4)
	@Max(value = 100)
	@Min(0)
	public BigDecimal getDescue() {
		return this.descue;
	}

	public void setDescue(BigDecimal descue) {
		this.descue = descue;
	}

	@Column(name = "COSTO", nullable = false, precision = 12, scale = 6)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	@Column(name = "NOTA", length = 1024)
	public String getNota() {
		return nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}
	
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "egreDeta")
	public Set<EgreDeta> getEgreDetas() {
		return egreDetas;
	}

	public void setEgreDetas(Set<EgreDeta> egreDetas) {
		this.egreDetas = egreDetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "egreDeta", cascade = { CascadeType.PERSIST, CascadeType.REMOVE, CascadeType.MERGE})
	public Set<EgreDetaImpu> getEgreDetaImpus() {
		return this.egreDetaImpus;
	}

	public void setEgreDetaImpus(Set<EgreDetaImpu> egreDetaImpus) {
		this.egreDetaImpus = egreDetaImpus;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="egreDeta")
    public Set<Kardex> getKardexs() {
        return this.kardexs;
    }
    
    public void setKardexs(Set<Kardex> kardexs) {
        this.kardexs = kardexs;
    }
	
    @Transient
	public BigDecimal getPrecioConImpu() {
		return precioConImpu;
	}

    public void setPrecioConImpu(BigDecimal precioConImpu) {
		this.precioConImpu = precioConImpu;
	}

	@Transient
	public BigDecimal getTotalConImpu() {
		return totalConImpu;
	}

	public void setTotalConImpu(BigDecimal totalConImpu) {
		this.totalConImpu = totalConImpu;
	}

	@Transient
    public BigDecimal getTotal() {
		return total;
	}
	
	public void setTotal(BigDecimal total) {
		this.total = total;
	}

}
