package ec.com.tecnointel.soem.tesoreria.modelo;
// Generated 27/01/2021 19:41:12 by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedSubgraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;

import ec.com.tecnointel.soem.parametro.modelo.FormPago;

/**
 * FpmeFormPago generated by hbm2java
 */
@Entity
@Table(name = "fpme_form_pago", schema = "public")
@NamedEntityGraph(name = "fpmeFormPago.Graph", attributeNodes = { 
@NamedAttributeNode(value = "formPago", subgraph = "dimm.Graph"),
@NamedAttributeNode(value = "formPagoMoviEgre")},
subgraphs = { @NamedSubgraph
		(
			name = "dimm.Graph", attributeNodes = {
				@NamedAttributeNode(value = "dimm")
			}
		)				
	} 
)
public class FpmeFormPago implements Serializable {

	private Integer fpmeFormPagoId;
	private FormPago formPago;
	private FormPagoMoviEgre formPagoMoviEgre;
	private Date fecha;
	private short diasPlaz;
	private BigDecimal totalReci;
	private String refere;
	
	private Set<CobrDeta> cobrDetas = new HashSet<CobrDeta>(0); 

	private static final long serialVersionUID = -3707745285033429995L;

	public FpmeFormPago() {
	}

	public FpmeFormPago(FormPagoMoviEgre formPagoMoviEgre) {
		this.formPagoMoviEgre = formPagoMoviEgre;
	}

	public FpmeFormPago(Integer fpmeFormPagoId, FormPago formPago, FormPagoMoviEgre formPagoMoviEgre, Date fecha,
			short diasPlaz, BigDecimal totalReci, String refere, Set<CobrDeta> cobrDetas) {
		this.fpmeFormPagoId = fpmeFormPagoId;
		this.formPago = formPago;
		this.formPagoMoviEgre = formPagoMoviEgre;
		this.fecha = fecha;
		this.diasPlaz = diasPlaz;
		this.totalReci = totalReci;
		this.refere = refere;
		
		this.cobrDetas = cobrDetas;
	}

	@Id
	@TableGenerator(name = "idFpmeFormPago", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "fpme_form_pago", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idFpmeFormPago")
	@Column(name = "fpme_form_pago_id", unique = true, nullable = false)
	public Integer getFpmeFormPagoId() {
		return this.fpmeFormPagoId;
	}

	public void setFpmeFormPagoId(Integer fpmeFormPagoId) {
		this.fpmeFormPagoId = fpmeFormPagoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "form_pago_id", nullable = false)
	public FormPago getFormPago() {
		return this.formPago;
	}

	public void setFormPago(FormPago formPago) {
		this.formPago = formPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fpme_id", nullable = false)
	public FormPagoMoviEgre getFormPagoMoviEgre() {
		return this.formPagoMoviEgre;
	}

	public void setFormPagoMoviEgre(FormPagoMoviEgre formPagoMoviEgre) {
		this.formPagoMoviEgre = formPagoMoviEgre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Min(0)
	@Column(name = "DIAS_PLAZ", nullable = false)
	public short getDiasPlaz() {
		return this.diasPlaz;
	}

	public void setDiasPlaz(short diasPlaz) {
		this.diasPlaz = diasPlaz;
	}

	@Column(name = "total_reci", nullable = false, precision = 14, scale = 6)
	public BigDecimal getTotalReci() {
		return this.totalReci;
	}

	public void setTotalReci(BigDecimal totalReci) {
		this.totalReci = totalReci;
	}

	@Column(name = "refere", length = 32)
	public String getRefere() {
		return this.refere;
	}

	public void setRefere(String refere) {
		this.refere = refere;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fpmeFormPago")
	public Set<CobrDeta> getCobrDetas() {
		return this.cobrDetas;
	}

	public void setCobrDetas(Set<CobrDeta> cobrDetas) {
		this.cobrDetas = cobrDetas;
	}

	
}
