package ec.com.tecnointel.soem.tesoreria.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.NamedSubgraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * PagoDeta generated by hbm2java
 */
@Entity
@Table(name = "pago_deta")
@NamedEntityGraph(name = "pagoDeta.Graph", attributeNodes =
	{
		@NamedAttributeNode(value = "cxp", subgraph = "ingreso.Graph"),
		@NamedAttributeNode(value = "formPagoMoviIngr")
	} , 
	subgraphs = {
				@NamedSubgraph(
								name = "ingreso.Graph", attributeNodes = {
										@NamedAttributeNode(value = "ingreso", subgraph = "persProv.Graph")
								}
							),  
				@NamedSubgraph(
						name = "persProv.Graph", attributeNodes = {
								@NamedAttributeNode(value = "persProv")
						}
					)				
				}  

)
public class PagoDeta implements java.io.Serializable {

	private Integer pagoDetaId;
	private Integer ingresoId;
	private Cxp cxp;
	private FormPagoMoviIngr formPagoMoviIngr;
	private BigDecimal total;

	private static final long serialVersionUID = -3909227637039323273L;

	public PagoDeta() {
	}
	
	public PagoDeta(Integer pagoDetaId, Integer ingresoId, BigDecimal total, Cxp cxp, FormPagoMoviIngr formPagoMoviIngr) {
		this.pagoDetaId = pagoDetaId;
		this.ingresoId = ingresoId;
		this.total = total;
		this.cxp = cxp;
		this.formPagoMoviIngr = formPagoMoviIngr;
	}

	@Id
	@TableGenerator(name = "idPagoDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "pago_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idPagoDeta")
	@Column(name = "PAGO_DETA_ID", unique = true, nullable = false)
	public Integer getPagoDetaId() {
		return this.pagoDetaId;
	}

	public void setPagoDetaId(Integer pagoDetaId) {
		this.pagoDetaId = pagoDetaId;
	}

	// Columna solo de referencia para saber de que documento del modulo del compras es el pago
	@Column(name = "INGRESO_ID")
	public Integer getIngresoId() {
		return ingresoId;
	}

	public void setIngresoId(Integer ingresoId) {
		this.ingresoId = ingresoId;
	}
	
	@Column(name = "TOTAL", nullable = false, precision = 14, scale = 6)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CXP_ID", nullable = false)
	public Cxp getCxp() {
		return this.cxp;
	}

	public void setCxp(Cxp cxp) {
		this.cxp = cxp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FPMI_ID", nullable = false)
	public FormPagoMoviIngr getFormPagoMoviIngr() {
		return this.formPagoMoviIngr;
	}

	public void setFormPagoMoviIngr(FormPagoMoviIngr formPagoMoviIngr) {
		this.formPagoMoviIngr = formPagoMoviIngr;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pagoDetaId == null) ? 0 : pagoDetaId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PagoDeta other = (PagoDeta) obj;
		if (pagoDetaId == null) {
			if (other.pagoDetaId != null)
				return false;
		} else if (!pagoDetaId.equals(other.pagoDetaId))
			return false;
		return true;
	}	
}
