package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import ec.com.tecnointel.soem.contabilidad.modelo.PlanCuen;

/**
 * ProdTipoPlanCuen generated by hbm2java
 */
@Entity
@Table(name = "prod_tipo_plan_cuen")
@NamedEntityGraph(name = "ptpc.Graph", attributeNodes = {
@NamedAttributeNode(value = "prodTipo"),
@NamedAttributeNode(value = "planCuen") })
public class ProdTipoPlanCuen implements java.io.Serializable {

	private Integer ptpcId;
	private PlanCuen planCuen;
	private ProdTipo prodTipo;
	private String tipoTran;

	private static final long serialVersionUID = -2596904097337613665L;

	public ProdTipoPlanCuen() {
	}

	public ProdTipoPlanCuen(Integer ptpcId, PlanCuen planCuen, ProdTipo prodTipo, String tipoTran) {
		this.ptpcId = ptpcId;
		this.planCuen = planCuen;
		this.prodTipo = prodTipo;
		this.tipoTran = tipoTran;
	}

	@Id
	@TableGenerator(name = "idProdTipoPlanCuen", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_tipo_plan_cuen", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdTipoPlanCuen")
	@Column(name = "PTPC_ID", unique = true, nullable = false)
	public Integer getPtpcId() {
		return this.ptpcId;
	}

	public void setPtpcId(Integer ptpcId) {
		this.ptpcId = ptpcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_TIPO_ID", nullable = false)
	public ProdTipo getProdTipo() {
		return this.prodTipo;
	}

	public void setProdTipo(ProdTipo prodTipo) {
		this.prodTipo = prodTipo;
	}

	@Column(name = "TIPO_TRAN", nullable = false)
	public String getTipoTran() {
		return tipoTran;
	}

	public void setTipoTran(String tipoTran) {
		this.tipoTran = tipoTran;
	}	
}
