package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import ec.com.tecnointel.soem.contabilidad.modelo.PlanCuen;
import ec.com.tecnointel.soem.parametro.modelo.Documento;

/**
 * ProdGrupPlanCuen generated by hbm2java
 */
@Entity
@Table(name = "prod_grup_plan_cuen")
@NamedEntityGraph(name = "prodgpc.Graph", attributeNodes = { 
@NamedAttributeNode(value = "prodGrup"),
@NamedAttributeNode(value = "planCuen"), 
@NamedAttributeNode(value = "documento") })
public class ProdGrupPlanCuen implements java.io.Serializable {

	private Integer pgpcId;
	private PlanCuen planCuen;
	private ProdGrup prodGrup;
	private Documento documento;
	private String tipoTran;

	private static final long serialVersionUID = -3707288333036470569L;

	public ProdGrupPlanCuen() {
	}

	public ProdGrupPlanCuen(Integer pgpcId, PlanCuen planCuen, ProdGrup prodGrup, String tipoTran) {
		this.pgpcId = pgpcId;
		this.planCuen = planCuen;
		this.prodGrup = prodGrup;
		this.tipoTran = tipoTran;
	}

	@Id
	@TableGenerator(name = "idProdGrupPlanCuen", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_grup_plan_cuen", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdGrupPlanCuen")
	@Column(name = "PGPC_ID", unique = true, nullable = false)
	public Integer getPgpcId() {
		return pgpcId;
	}

	public void setPgpcId(Integer pgpcId) {
		this.pgpcId = pgpcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_GRUP_ID", nullable = false)
	public ProdGrup getProdGrup() {
		return prodGrup;
	}

	public void setProdGrup(ProdGrup prodGrup) {
		this.prodGrup = prodGrup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENTO_ID", nullable = false)
	public Documento getDocumento() {
		return documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "TIPO_TRAN", nullable = false)
	public String getTipoTran() {
		return tipoTran;
	}

	public void setTipoTran(String tipoTran) {
		this.tipoTran = tipoTran;
	}

}
