package ec.com.tecnointel.soem.inventario.modelo;
// Generated 16/09/2020 9:14:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import ec.com.tecnointel.soem.parametro.modelo.Bodega;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;

/**
 * TomaFisi generated by hbm2java
 */
@Entity
@Table(name = "toma_fisi")
@NamedEntityGraph(name = "tomaFisi.Graph", attributeNodes = { 
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "bodega") })
public class TomaFisi implements java.io.Serializable {

	private Integer tomaFisiId;
	private Sucursal sucursal;
	private Bodega bodega;
	private Date fechaRegi;
	private Date fechaProc;
	private Integer numero;
	private String refere;
	private String nota;
	private String estado;
	private Set<TomaFisiDeta> tomaFisiDetas = new HashSet<TomaFisiDeta>(0);

	private static final long serialVersionUID = 3015251656833304228L;

	public TomaFisi() {
	}

	public TomaFisi(Integer tomaFisiId, Sucursal sucursal, Bodega bodega, Date fechaRegi, Date fechaProc, Integer numero,
			String refere, String nota, String estado) {
		this.tomaFisiId = tomaFisiId;
		this.sucursal = sucursal;
		this.bodega = bodega;
		this.fechaRegi = fechaRegi;
		this.fechaProc = fechaProc;
		this.numero = numero;
		this.refere = refere;
		this.nota = nota;
		this.estado = estado;
	}

	public TomaFisi(Integer tomaFisiId, Sucursal sucursal, Bodega bodega, Date fechaRegi, Date fechaProc, Integer numero,
			String refere, String nota, String estado, Set<TomaFisiDeta> tomaFisiDetas) {
		this.tomaFisiId = tomaFisiId;
		this.sucursal = sucursal;
		this.bodega = bodega;
		this.fechaRegi = fechaRegi;
		this.fechaProc = fechaProc;
		this.numero = numero;
		this.refere = refere;
		this.nota = nota;
		this.estado = estado;
		this.tomaFisiDetas = tomaFisiDetas;
	}

	@Id
	@TableGenerator(name = "idTomaFisi", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "toma_fisi", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTomaFisi")	
	@Column(name = "toma_fisi_id", unique = true, nullable = false)
	public Integer getTomaFisiId() {
		return tomaFisiId;
	}

	public void setTomaFisiId(Integer tomaFisiId) {
		this.tomaFisiId = tomaFisiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sucursal_id", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bodega_id", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_regi", nullable = false, length = 13)
	public Date getFechaRegi() {
		return this.fechaRegi;
	}

	public void setFechaRegi(Date fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_proc", nullable = false, length = 13)
	public Date getFechaProc() {
		return this.fechaProc;
	}

	public void setFechaProc(Date fechaProc) {
		this.fechaProc = fechaProc;
	}

	@Column(name = "numero", nullable = false, precision = 9, scale = 0)
	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "refere", nullable = true)
	public String getRefere() {
		return this.refere;
	}

	public void setRefere(String refere) {
		this.refere = refere;
	}

	@Column(name = "nota", nullable = true)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "estado", nullable = false, length = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tomaFisi")
	public Set<TomaFisiDeta> getTomaFisiDetas() {
		return this.tomaFisiDetas;
	}

	public void setTomaFisiDetas(Set<TomaFisiDeta> tomaFisiDetas) {
		this.tomaFisiDetas = tomaFisiDetas;
	}
}
