package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.validation.constraints.Size;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "sucu_para")
@NamedEntityGraph(name = "sucuPara.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"), 
@NamedAttributeNode(value = "parametro") })
public class SucuPara implements Serializable {

	private Integer sucuParaId;
	private String descri;
	private Boolean estado;
	
	private Sucursal sucursal;
	private Parametro parametro;

	private static final long serialVersionUID = -6938142654603909138L;

	public SucuPara() {
	}

	public SucuPara(Sucursal sucursal, Parametro parametro, boolean estado) {
		this.estado = estado;
		this.sucursal = sucursal;
		this.parametro = parametro;
	}

	@Id
	@TableGenerator(name = "idSucuPara", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "sucu_para", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idSucuPara")
	@Column(name = "SUCU_PARA_ID", unique = true, nullable = false)
	public Integer getSucuParaId() {
		return sucuParaId;
	}

	public void setSucuParaId(Integer sucuParaId) {
		this.sucuParaId = sucuParaId;
	}

	@Size(max = 100, min = 1, message = "Solo puede ingresar 100 caracteres")
	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "estado", nullable = false)
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARAMETRO_ID", nullable = false)
	public Parametro getParametro() {
		return parametro;
	}

	public void setParametro(Parametro parametro) {
		this.parametro = parametro;
	}
}
