package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmplHoraPlan generated by hbm2java
 */
@Entity
@Table(name = "empl_hora_plan")
public class EmplHoraPlan implements java.io.Serializable {

	private Integer emplHoraPlanId;
	private HoraPlan horaPlan;
	private PersEmpl persEmpl;
	private Date fechaDesd;
	private Date fechaHast;

	private static final long serialVersionUID = 5729495670356042878L;

	public EmplHoraPlan() {
	}

	public EmplHoraPlan(Integer emplHoraPlanId, HoraPlan horaPlan,
			PersEmpl persEmpl, Date fechaDesd, Date fechaHast) {
		this.emplHoraPlanId = emplHoraPlanId;
		this.horaPlan = horaPlan;
		this.persEmpl = persEmpl;
		this.fechaDesd = fechaDesd;
		this.fechaHast = fechaHast;
	}

	@Id
	@TableGenerator(name = "idEmplHoraPlan", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_hora_plan", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplHoraPlan")
	@Column(name = "empl_hora_plan_id", unique = true, nullable = false)
	public Integer getEmplHoraPlanId() {
		return this.emplHoraPlanId;
	}

	public void setEmplHoraPlanId(Integer emplHoraPlanId) {
		this.emplHoraPlanId = emplHoraPlanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hora_plan_id", nullable = false)
	public HoraPlan getHoraPlan() {
		return this.horaPlan;
	}

	public void setHoraPlan(HoraPlan horaPlan) {
		this.horaPlan = horaPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_desd", nullable = false, length = 13)
	public Date getFechaDesd() {
		return this.fechaDesd;
	}

	public void setFechaDesd(Date fechaDesd) {
		this.fechaDesd = fechaDesd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_hast", nullable = false, length = 13)
	public Date getFechaHast() {
		return this.fechaHast;
	}

	public void setFechaHast(Date fechaHast) {
		this.fechaHast = fechaHast;
	}

}
