package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import ec.com.tecnointel.soem.parametro.modelo.FormPago;

/**
 * RolFormPago generated by hbm2java
 */
@Entity
@Table(name = "rol_form_pago")
@NamedEntityGraph(name = "rolFormPago.Graph", attributeNodes = {
@NamedAttributeNode(value = "rol"), 
@NamedAttributeNode(value = "formPago") })
public class RolFormPago implements java.io.Serializable {

	private Integer rolFormPagoId;
	private FormPago formPago;
	private Rol rol;
	private Boolean predet;
	private Boolean acceso;

	private static final long serialVersionUID = -6733680340281439636L;

	public RolFormPago() {
	}

	public RolFormPago(Integer rolFormPagoId, FormPago formPago, Rol rol, Boolean predet, Boolean acceso) {
		this.rolFormPagoId = rolFormPagoId;
		this.formPago = formPago;
		this.rol = rol;
		this.predet = predet;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idRolFormPago", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "rol_form_pago", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRolFormPago")
	@Column(name = "ROL_FORM_PAGO_ID", unique = true, nullable = false)
	public Integer getRolFormPagoId() {
		return this.rolFormPagoId;
	}

	public void setRolFormPagoId(Integer rolFormPagoId) {
		this.rolFormPagoId = rolFormPagoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORM_PAGO_ID", nullable = false)
	public FormPago getFormPago() {
		return this.formPago;
	}

	public void setFormPago(FormPago formPago) {
		this.formPago = formPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "PREDET", nullable = false)
	public Boolean getPredet() {
		return predet;
	}

	public void setPredet(Boolean predet) {
		this.predet = predet;
	}
	
	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((formPago == null) ? 0 : formPago.hashCode());
		result = prime * result + ((rol == null) ? 0 : rol.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RolFormPago other = (RolFormPago) obj;
		if (formPago == null) {
			if (other.formPago != null)
				return false;
		} else if (!formPago.equals(other.formPago))
			return false;
		if (rol == null) {
			if (other.rol != null)
				return false;
		} else if (!rol.equals(other.rol))
			return false;
		return true;
	}
	
}
